# Generated by Django 5.2 on 2025-04-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("employees", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
            ],
        ),
    ]
