# Generated by Django 5.2 on 2025-04-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("excel_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
    ]
